---
AWSTemplateFormatVersion: 2010-09-09
Description: CFT template to create a Lambda function to retrieve key/value from
  SSM parameter and store it in S3 bucket.

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: arn:aws:ssm:us-east-1:637423619688:parameter/UserName
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: arn:aws:s3:::ssm-s3-08032024/*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:us-east-1:637423619688:ExerciseLambda
  ExerciseLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Timeout: 60
      Code:
        ZipFile: |
            import boto3

            s3_client = boto3.client('s3')

            ssm_client = boto3.client('ssm')


            def handler(event, context):
                parameter_name = "UserName"
                bucket_name = "ssm-s3-08032024"
                  
                parameter_response = ssm_client.get_parameter(Name=parameter_name)
                  
                user_name = parameter_response['Parameter']['Value']
                  
                print(user_name)
                  
                file_name = "UserName.txt"
                  
                s3_client.put_object(Body=user_name, Bucket=bucket_name, Key=file_name) 
                      

Outputs:
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: ExerciseLambda.Arn
